Update pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-# Version 0.2.2
+# Version 0.3.0
 name: UPM Deployment
 
 env:
@@ -63,7 +63,7 @@ jobs:
           then
             goo transform hide-folder "Samples"
             goo package ignore-folder . "Samples"
-            goo transform hide-folder "Tests"
+            #goo transform hide-folder "Tests"
           fi
 
       - name: Deploy Package
@@ -71,7 +71,13 @@ jobs:
         env:
           REPO: self
           BRANCH: upm
-          FOLDER: "\"$PACKAGE_ROOT\""
+          FOLDER: \"$PACKAGE_ROOT\"
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           MESSAGE: "Deploy: {sha} (v${{env.VERSION}})"
-
+      
+      - name: Tag UPM branch
+        run: |
+          git fetch origin upm
+          git checkout -f upm
+          git tag v${{env.VERSION}} HEAD
+          git push --tags || echo "Warning: tag failed. Does version ${{env.VERSION}} already exist in the repository?"
